-- 20fit Workout — starter Exercise library (28 movements, mixed coach + rehab/dokter).
-- Applied to project cpvzwqptzcxnwzfzgrmt on 2026-09-08 as draft rows with empty
-- video_url — staff attach a video (YouTube link or upload) then publish. Idempotent
-- (on conflict do nothing). otot/alat/level use the CMS form vocabulary.

insert into public.w20fit_exercises
(nama, slug, video_url, thumbnail_url, deskripsi, cue_teknik, otot_target, level, alat, durasi_detik, kontraindikasi, status)
values
('Heel Slide', 'heel-slide', '', '', 'Latihan mobilisasi lutut awal pascacedera atau pascaoperasi.', array['Geser tumit pelan mendekati bokong','Jangan menahan napas','Berhenti bila nyeri tajam']::text[], array['Paha','Betis']::text[], 'pemula', array['matras']::text[], null, 'Hindari bila ada bengkak akut atau nyeri hebat.', 'draft'),
('Quad Set', 'quad-set', '', '', 'Aktivasi otot paha depan tanpa menggerakkan sendi.', array['Kencangkan otot paha depan, dorong lutut ke matras','Tahan 5-10 detik lalu lepas','Napas tetap teratur']::text[], array['Paha']::text[], 'pemula', array['matras']::text[], 10, null, 'draft'),
('Straight Leg Raise', 'straight-leg-raise', '', '', 'Menguatkan paha depan tanpa membebani sendi lutut.', array['Kunci lutut lurus sebelum mengangkat','Angkat setinggi lutut sisi lain','Turunkan perlahan']::text[], array['Paha','Core']::text[], 'pemula', array['matras']::text[], null, 'Hentikan bila memicu nyeri pinggang bawah.', 'draft'),
('Glute Bridge', 'glute-bridge', '', '', 'Mengaktifkan bokong dan menstabilkan panggul.', array['Tekan tumit, angkat pinggul sampai lurus','Remas bokong di atas','Jangan melengkungkan pinggang berlebihan']::text[], array['Bokong','Core']::text[], 'pemula', array['matras']::text[], null, null, 'draft'),
('Clamshell', 'clamshell', '', '', 'Menguatkan otot bokong samping untuk stabilitas panggul.', array['Tumit rapat, buka lutut seperti kerang','Panggul tetap menghadap depan','Gerak terkontrol']::text[], array['Bokong']::text[], 'pemula', array['matras','resistance band']::text[], null, null, 'draft'),
('Bird Dog', 'bird-dog', '', '', 'Melatih stabilitas inti dan koordinasi.', array['Julurkan lengan dan kaki berlawanan','Jaga punggung datar, panggul stabil','Tahan sejenak lalu ganti sisi']::text[], array['Core','Punggung']::text[], 'pemula', array['matras']::text[], null, null, 'draft'),
('Dead Bug', 'dead-bug', '', '', 'Kontrol inti dengan pinggang tetap netral.', array['Punggung bawah menempel matras','Turunkan lengan & kaki berlawanan','Jangan biarkan pinggang terangkat']::text[], array['Core']::text[], 'pemula', array['matras']::text[], null, null, 'draft'),
('Cat-Cow', 'cat-cow', '', '', 'Mobilisasi tulang belakang, pemanasan punggung.', array['Bergantian membulatkan dan melengkungkan punggung','Ikuti irama napas','Gerak halus tanpa dipaksa']::text[], array['Punggung','Core']::text[], 'pemula', array['matras']::text[], null, null, 'draft'),
('Pelvic Tilt', 'pelvic-tilt', '', '', 'Melatih kontrol panggul dan inti dalam.', array['Ratakan punggung bawah ke matras','Kencangkan perut bawah','Lepas perlahan']::text[], array['Core','Punggung']::text[], 'pemula', array['matras']::text[], null, null, 'draft'),
('Ankle Pump', 'ankle-pump', '', '', 'Melancarkan sirkulasi & mobilitas pergelangan kaki.', array['Gerakkan pergelangan kaki naik-turun','Rentang penuh dan pelan','Boleh kedua kaki bergantian']::text[], array['Betis']::text[], 'pemula', array['tanpa alat']::text[], null, null, 'draft'),
('Calf Raise', 'calf-raise', '', '', 'Menguatkan betis dan pergelangan kaki.', array['Angkat tumit setinggi mungkin','Pegangan kursi untuk keseimbangan','Turun perlahan']::text[], array['Betis']::text[], 'pemula', array['tanpa alat','kursi']::text[], null, null, 'draft'),
('Wall Sit', 'wall-sit', '', '', 'Menguatkan paha secara isometrik.', array['Punggung menempel dinding, lutut 90 derajat','Berat di tumit','Napas teratur selama menahan']::text[], array['Paha','Bokong']::text[], 'menengah', array['tanpa alat']::text[], 45, 'Hati-hati pada nyeri lutut depan (patellofemoral).', 'draft'),
('Scapular Retraction', 'scapular-retraction', '', '', 'Aktivasi otot penstabil bahu & postur.', array['Tarik tulang belikat ke bawah dan ke tengah','Bahu jauh dari telinga','Gerak kecil terkontrol']::text[], array['Punggung','Bahu']::text[], 'pemula', array['resistance band']::text[], null, null, 'draft'),
('Shoulder Pendulum', 'shoulder-pendulum', '', '', 'Mobilisasi bahu ringan pascacedera.', array['Badan condong, lengan menggantung rileks','Ayun lembut memutar','Biarkan momentum, jangan dipaksa']::text[], array['Bahu']::text[], 'pemula', array['tanpa alat']::text[], null, 'Hentikan bila nyeri meningkat.', 'draft'),
('Standing Hip Abduction', 'standing-hip-abduction', '', '', 'Menguatkan bokong samping sambil berdiri.', array['Angkat kaki lurus ke samping','Badan tetap tegak, jangan miring','Turun perlahan']::text[], array['Bokong','Paha']::text[], 'pemula', array['kursi','resistance band']::text[], null, null, 'draft'),
('Wall Push Up', 'wall-push-up', '', '', 'Versi ringan push up untuk pemula.', array['Telapak di dinding selebar bahu','Turun dengan siku terkontrol','Tubuh lurus dari kepala ke tumit']::text[], array['Dada','Lengan']::text[], 'pemula', array['tanpa alat']::text[], null, null, 'draft'),
('Push Up', 'push-up', '', '', 'Latihan dorong tubuh atas dengan berat badan.', array['Tubuh lurus, inti kencang','Turun sampai dada dekat lantai','Siku sekitar 45 derajat']::text[], array['Dada','Lengan','Core']::text[], 'menengah', array['tanpa alat']::text[], null, null, 'draft'),
('Bodyweight Squat', 'bodyweight-squat', '', '', 'Pola jongkok dasar untuk tubuh bawah.', array['Kaki selebar bahu, dada tegak','Turun seperti duduk, lutut searah jari kaki','Dorong lewat tumit']::text[], array['Paha','Bokong']::text[], 'pemula', array['tanpa alat']::text[], null, null, 'draft'),
('Goblet Squat', 'goblet-squat', '', '', 'Squat berbeban untuk kekuatan tubuh bawah.', array['Pegang beban di depan dada','Turun dalam, punggung netral','Dorong naik lewat tumit']::text[], array['Paha','Bokong','Core']::text[], 'menengah', array['dumbbell','kettlebell']::text[], null, null, 'draft'),
('Forward Lunge', 'forward-lunge', '', '', 'Latihan satu kaki untuk kekuatan & keseimbangan.', array['Melangkah, turunkan lutut belakang','Lutut depan searah jari kaki','Dorong kembali ke berdiri']::text[], array['Paha','Bokong']::text[], 'menengah', array['tanpa alat']::text[], null, null, 'draft'),
('Step-up', 'step-up', '', '', 'Pola naik-tangga untuk tubuh bawah.', array['Naik penuh dengan satu kaki','Dorong lewat tumit, badan tegak','Turun perlahan terkontrol']::text[], array['Paha','Bokong']::text[], 'menengah', array['kursi']::text[], null, null, 'draft'),
('Plank', 'plank', '', '', 'Menahan stabilitas inti secara isometrik.', array['Tubuh lurus, inti & bokong kencang','Bahu di atas siku','Jangan biarkan pinggul turun']::text[], array['Core','Bahu']::text[], 'menengah', array['matras']::text[], 40, null, 'draft'),
('Side Plank', 'side-plank', '', '', 'Menguatkan inti samping (obliques).', array['Tumpu satu siku, tubuh lurus menyamping','Angkat pinggul','Jangan memelintir badan']::text[], array['Core']::text[], 'menengah', array['matras']::text[], 30, null, 'draft'),
('Romanian Deadlift', 'romanian-deadlift', '', '', 'Pola hip hinge untuk rantai belakang.', array['Dorong pinggul ke belakang, lutut sedikit tekuk','Punggung netral sepanjang gerak','Rasakan regangan paha belakang']::text[], array['Bokong','Paha','Punggung']::text[], 'menengah', array['dumbbell']::text[], null, 'Hentikan bila memicu nyeri pinggang.', 'draft'),
('Bent-over Row', 'bent-over-row', '', '', 'Latihan tarik untuk punggung.', array['Condong dari pinggul, punggung datar','Tarik siku ke belakang, remas belikat','Turun perlahan']::text[], array['Punggung','Lengan']::text[], 'menengah', array['dumbbell','resistance band']::text[], null, null, 'draft'),
('Overhead Press', 'overhead-press', '', '', 'Dorong ke atas untuk kekuatan bahu.', array['Inti kencang, dorong beban ke atas','Jangan melengkungkan pinggang','Turun terkontrol ke bahu']::text[], array['Bahu','Lengan']::text[], 'menengah', array['dumbbell']::text[], null, null, 'draft'),
('Mountain Climber', 'mountain-climber', '', '', 'Kardio-inti berintensitas.', array['Posisi plank, tarik lutut bergantian ke dada','Pinggul tetap rendah','Jaga ritme napas']::text[], array['Core','Full body']::text[], 'menengah', array['matras']::text[], 40, null, 'draft'),
('Kettlebell Swing', 'kettlebell-swing', '', '', 'Pola hip hinge eksplosif, kardio & kekuatan.', array['Tenaga dari dorongan pinggul, bukan lengan','Punggung netral','Ayun sampai setinggi dada']::text[], array['Bokong','Punggung','Full body']::text[], 'lanjutan', array['kettlebell']::text[], null, 'Butuh teknik hip hinge yang benar; hati-hati pada masalah pinggang.', 'draft')
on conflict do nothing;
